/*
 * DiveHub.WebApi | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DiveHub.ClientApi.Client.OpenAPIDateConverter;

namespace DiveHub.ClientApi.Model
{
    /// <summary>
    /// DiveSavePhotoDto
    /// </summary>
    [DataContract(Name = "DiveSavePhotoDto")]
    public partial class DiveSavePhotoDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DiveSavePhotoDto" /> class.
        /// </summary>
        /// <param name="fileName">fileName.</param>
        /// <param name="url">url.</param>
        /// <param name="createdAt">createdAt.</param>
        public DiveSavePhotoDto(string fileName = default(string), string url = default(string), DateTime? createdAt = default(DateTime?))
        {
            this.fileName = fileName;
            this.url = url;
            this.createdAt = createdAt;
        }

        /// <summary>
        /// Gets or Sets fileName
        /// </summary>
        [DataMember(Name = "fileName", EmitDefaultValue = false)]
        public string fileName { get; set; }

        /// <summary>
        /// Gets or Sets url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string url { get; set; }

        /// <summary>
        /// Gets or Sets createdAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = true)]
        public DateTime? createdAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DiveSavePhotoDto {\n");
            sb.Append("  fileName: ").Append(fileName).Append("\n");
            sb.Append("  url: ").Append(url).Append("\n");
            sb.Append("  createdAt: ").Append(createdAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
