/*
 * DiveHub.WebApi | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DiveHub.ClientApi.Client.OpenAPIDateConverter;

namespace DiveHub.ClientApi.Model
{
    /// <summary>
    /// DivePointDto
    /// </summary>
    [DataContract(Name = "DivePointDto")]
    public partial class DivePointDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DivePointDto" /> class.
        /// </summary>
        /// <param name="divePointId">divePointId.</param>
        /// <param name="diveId">diveId.</param>
        /// <param name="latitude">latitude.</param>
        /// <param name="longitude">longitude.</param>
        /// <param name="description">description.</param>
        public DivePointDto(int divePointId = default(int), int diveId = default(int), double latitude = default(double), double longitude = default(double), string description = default(string))
        {
            this.divePointId = divePointId;
            this.diveId = diveId;
            this.latitude = latitude;
            this.longitude = longitude;
            this.description = description;
        }

        /// <summary>
        /// Gets or Sets divePointId
        /// </summary>
        [DataMember(Name = "divePointId", EmitDefaultValue = false)]
        public int divePointId { get; set; }

        /// <summary>
        /// Gets or Sets diveId
        /// </summary>
        [DataMember(Name = "diveId", EmitDefaultValue = false)]
        public int diveId { get; set; }

        /// <summary>
        /// Gets or Sets latitude
        /// </summary>
        [DataMember(Name = "latitude", EmitDefaultValue = false)]
        public double latitude { get; set; }

        /// <summary>
        /// Gets or Sets longitude
        /// </summary>
        [DataMember(Name = "longitude", EmitDefaultValue = false)]
        public double longitude { get; set; }

        /// <summary>
        /// Gets or Sets description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DivePointDto {\n");
            sb.Append("  divePointId: ").Append(divePointId).Append("\n");
            sb.Append("  diveId: ").Append(diveId).Append("\n");
            sb.Append("  latitude: ").Append(latitude).Append("\n");
            sb.Append("  longitude: ").Append(longitude).Append("\n");
            sb.Append("  description: ").Append(description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
